version: '3'

volumes:
  theatre-db-data:
  static:
  media:

services:
  service:
    build: app
    volumes:
      - static:/var/www/static
      - media:/var/www/media
    expose:
      - "8000"
    env_file:
      - ./.env


  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/var/www/static
      - media:/var/www/media
    depends_on:
      - service
    ports:
      - "80:80"

  theatre-db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - $HOME/postgresql/data:/var/lib/postgresql/data
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql
    expose:
      - "5432"
