version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - 8010:8010
    volumes:
      - ./host_volume:/internal_volume
      - media:/media
  neighbour:
    image: curlimages/curl:latest # docker pull envoyproxy/envoy

    entrypoint: [ "curl", "-s", "backend:8010" ]
    depends_on:
    - backend
    restart: always
volumes:
  media:
